name: face_apps
description: A face recognition attendance app using Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_mlkit_face_detection: ^0.3.0
  http: ^1.1.0
  fluttertoast: ^8.0.9
  intl: ^0.18.0
  file_picker: ^5.2.0
  path_provider: ^2.0.10
  dio: ^5.0.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  form_builder_file_picker: ^4.0.0
  permission_handler: ^10.2.0
  image_picker: ^1.0.4
  rflutter_alert: ^2.0.4
  cached_network_image: ^3.2.0
  photo_view: ^0.14.0
  easy_pdf_viewer: ^1.0.1
  infinite_scroll_pagination: ^4.0.0
  open_file: ^3.2.1
  carousel_slider: ^4.0.0
  extended_image: ^8.1.0
  shared_preferences: ^2.0.13
  flare_flutter: ^3.0.2
  provider: ^6.0.0
  camera: ^0.10.5+9
  geolocator: ^9.0.2
  lottie: ^2.3.2
  geocoding: ^2.0.5
  dotted_border: ^2.0.0
  font_awesome_flutter: ^10.0.0
  http_parser: ^4.0.0
  tflite_flutter: ^0.10.4
  image: ^3.2.0
  package_info_plus: ^4.0.0

#  sqflite: ^2.2.5
#  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/raw/face_id_ring.json
    - assets/images/ic_absen.png
    - assets/images/ic_history.png
    - assets/images/ic_leave.png
    - assets/mobilefacenet.tflite
